student = {
	firstName: 'Tung',
	lastName: 'Bui',
	email: 'test@example.com',
	gender: 'F',
	country: 'Vietnam',
	isStudentActive: false,
	favouriteSubjects: ['maths', 'english', 'cs'],
	totalSpentInBooks: 0.0,
};

students = [
	{
		firstName: 'Tung1',
		lastName: 'Bui',
		email: 'test1@example.com',
		gender: 'F',
		country: 'Vietnam',
		isStudentActive: false,
		favouriteSubjects: ['maths', 'english', 'cs'],
		totalSpentInBooks: 0.0,
	},
	{
		firstName: 'Tung2',
		lastName: 'Bui',
		email: 'test2@example.com',
		gender: 'F',
		country: 'Vietnam',
		isStudentActive: false,
		favouriteSubjects: ['maths', 'english', 'cs'],
		totalSpentInBooks: 0.0,
	},
	{
		firstName: 'Tung3',
		lastName: 'Bui',
		email: 'test@example.com',
		gender: 'F',
		country: 'Vietnam',
		isStudentActive: false,
		favouriteSubjects: ['maths', 'english', 'cs'],
		totalSpentInBooks: 0.0,
	},
	{
		firstName: 'Tung3',
		lastName: 'Bui',
		email: 'test3@example.com',
		gender: 'F',
		country: 'Vietnam',
		isStudentActive: false,
		favouriteSubjects: ['maths', 'english', 'cs'],
		totalSpentInBooks: 0.0,
	},
	{
		firstName: 'Tung4',
		lastName: 'Bui',
		email: 'test4@example.com',
		gender: 'F',
		country: 'Vietnam',
		isStudentActive: false,
		favouriteSubjects: ['maths', 'english', 'cs'],
		totalSpentInBooks: 0.0,
	},
	{
		firstName: 'Tung5',
		lastName: 'Bui',
		email: 'test5@example.com',
		gender: 'F',
		country: 'Vietnam',
		isStudentActive: false,
		favouriteSubjects: ['maths', 'english', 'cs'],
		totalSpentInBooks: 0.0,
	},
	{
		firstName: 'Tung6',
		lastName: 'Bui',
		email: 'test6@example.com',
		gender: 'F',
		country: 'Vietnam',
		isStudentActive: false,
		favouriteSubjects: ['maths', 'english', 'cs'],
		totalSpentInBooks: 0.0,
	},
	{
		firstName: 'Tung7',
		lastName: 'Bui',
		email: 'test7@example.com',
		gender: 'F',
		country: 'Vietnam',
		isStudentActive: false,
		favouriteSubjects: ['maths', 'english', 'cs'],
		totalSpentInBooks: 0.0,
	},
	{
		firstName: 'Tung8',
		lastName: 'Bui',
		email: 'test8@example.com',
		gender: 'F',
		country: 'Vietnam',
		isStudentActive: false,
		favouriteSubjects: ['maths', 'english', 'cs'],
		totalSpentInBooks: 0.0,
	},
	{
		firstName: 'Tung9',
		lastName: 'Bui',
		email: 'test9@example.com',
		gender: 'F',
		country: 'Vietnam',
		isStudentActive: false,
		favouriteSubjects: ['maths', 'english', 'cs'],
		totalSpentInBooks: 0.0,
	},
	{
		firstName: 'Tung10',
		lastName: 'Bui',
		email: 'test10@example.com',
		gender: 'F',
		country: 'Vietnam',
		isStudentActive: false,
		favouriteSubjects: ['maths', 'english', 'cs'],
		totalSpentInBooks: 0.0,
	},
];
